import { StudentProfile } from '../types';

export const INITIAL_STUDENTS: StudentProfile[] = [
  {
    id: 'stu-1024',
    anonymousCode: 'STU-1024',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@campus.edu',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    department: 'Computer Science & Engineering',
    year: '1st Year (Semester 2)',
    status: 'check_in_recommended',
    consent: {
      optedIn: true,
      shareIndicatorsWithCounselor: true,
      allowAggregatedAdminStats: true,
      consentDate: '2026-07-15',
    },
    counselorNotes: 'Assigned to Dr. Ananya Sharma. First year transition follow-up.',
    checkIns: [
      {
        id: 'ck-101',
        studentId: 'stu-1024',
        date: '2026-08-01',
        weekNumber: 1,
        overallWellbeing: 4,
        academicStress: 2,
        sleepQuality: 4,
        energyLevel: 4,
        socialConnection: 4,
        concentration: 4,
        primaryTag: 'Routine',
        personalReflection: 'Orientation went well, feeling excited about coding labs and meeting hostel mates.',
        isPrivateNote: false,
      },
      {
        id: 'ck-102',
        studentId: 'stu-1024',
        date: '2026-08-08',
        weekNumber: 2,
        overallWellbeing: 4,
        academicStress: 2,
        sleepQuality: 4,
        energyLevel: 4,
        socialConnection: 4,
        concentration: 4,
        primaryTag: 'Routine',
        personalReflection: 'Lectures are engaging. Balance is good so far.',
        isPrivateNote: false,
      },
      {
        id: 'ck-103',
        studentId: 'stu-1024',
        date: '2026-08-15',
        weekNumber: 3,
        overallWellbeing: 3,
        academicStress: 3,
        sleepQuality: 3,
        energyLevel: 3,
        socialConnection: 3,
        concentration: 3,
        primaryTag: 'Projects',
        personalReflection: 'Data Structures assignment deadlines and lab submissions started piling up together.',
        isPrivateNote: false,
      },
      {
        id: 'ck-104',
        studentId: 'stu-1024',
        date: '2026-08-21',
        weekNumber: 4,
        overallWellbeing: 2,
        academicStress: 5,
        sleepQuality: 2,
        energyLevel: 2,
        socialConnection: 3,
        concentration: 2,
        primaryTag: 'Exams',
        personalReflection: 'Staying up until 3:30 AM every night to catch up on backlog. Brain feels foggy in morning lectures.',
        isPrivateNote: false,
      },
    ],
  },
  {
    id: 'stu-1182',
    anonymousCode: 'STU-1182',
    name: 'Priya Patel',
    email: 'priya.patel@campus.edu',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Bachelor of Computer Applications (BCA)',
    year: '2nd Year (Semester 3)',
    status: 'check_in_recommended',
    consent: {
      optedIn: true,
      shareIndicatorsWithCounselor: true,
      allowAggregatedAdminStats: true,
      consentDate: '2026-07-20',
    },
    counselorNotes: 'Noticed persistent sleep irregularities.',
    checkIns: [
      {
        id: 'ck-201',
        studentId: 'stu-1182',
        date: '2026-08-01',
        weekNumber: 1,
        overallWellbeing: 3,
        academicStress: 3,
        sleepQuality: 3,
        energyLevel: 3,
        socialConnection: 3,
        concentration: 4,
        primaryTag: 'Routine',
      },
      {
        id: 'ck-202',
        studentId: 'stu-1182',
        date: '2026-08-08',
        weekNumber: 2,
        overallWellbeing: 3,
        academicStress: 4,
        sleepQuality: 2,
        energyLevel: 3,
        socialConnection: 2,
        concentration: 3,
        primaryTag: 'Projects',
      },
      {
        id: 'ck-203',
        studentId: 'stu-1182',
        date: '2026-08-15',
        weekNumber: 3,
        overallWellbeing: 2,
        academicStress: 4,
        sleepQuality: 1,
        energyLevel: 2,
        socialConnection: 2,
        concentration: 2,
        primaryTag: 'Health',
        personalReflection: 'Insomnia flare up. Hard to focus in DBMS class.',
      },
      {
        id: 'ck-204',
        studentId: 'stu-1182',
        date: '2026-08-21',
        weekNumber: 4,
        overallWellbeing: 2,
        academicStress: 4,
        sleepQuality: 2,
        energyLevel: 1,
        socialConnection: 2,
        concentration: 1,
        primaryTag: 'Health',
        personalReflection: 'Feel exhausted throughout the day.',
      },
    ],
  },
  {
    id: 'stu-1231',
    anonymousCode: 'STU-1231',
    name: 'Rohan Verma',
    email: 'rohan.verma@campus.edu',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'MBA (Marketing)',
    year: '1st Year (Trimester 1)',
    status: 'check_in_recommended',
    consent: {
      optedIn: true,
      shareIndicatorsWithCounselor: true,
      allowAggregatedAdminStats: true,
      consentDate: '2026-07-22',
    },
    counselorNotes: 'Relocated from another state; monitoring campus integration.',
    checkIns: [
      {
        id: 'ck-301',
        studentId: 'stu-1231',
        date: '2026-08-01',
        weekNumber: 1,
        overallWellbeing: 4,
        academicStress: 2,
        sleepQuality: 4,
        energyLevel: 4,
        socialConnection: 3,
        concentration: 4,
        primaryTag: 'Routine',
      },
      {
        id: 'ck-302',
        studentId: 'stu-1231',
        date: '2026-08-08',
        weekNumber: 2,
        overallWellbeing: 3,
        academicStress: 3,
        sleepQuality: 3,
        energyLevel: 3,
        socialConnection: 2,
        concentration: 4,
        primaryTag: 'Social',
      },
      {
        id: 'ck-303',
        studentId: 'stu-1231',
        date: '2026-08-15',
        weekNumber: 3,
        overallWellbeing: 3,
        academicStress: 3,
        sleepQuality: 3,
        energyLevel: 3,
        socialConnection: 1,
        concentration: 3,
        primaryTag: 'Social',
        personalReflection: 'Feeling disconnected from cohort study groups, staying in room a lot.',
      },
      {
        id: 'ck-304',
        studentId: 'stu-1231',
        date: '2026-08-21',
        weekNumber: 4,
        overallWellbeing: 2,
        academicStress: 3,
        sleepQuality: 3,
        energyLevel: 2,
        socialConnection: 1,
        concentration: 3,
        primaryTag: 'Social',
        personalReflection: 'Homesick and finding it difficult to make new friends here.',
      },
    ],
  },
  {
    id: 'stu-1405',
    anonymousCode: 'STU-1405',
    name: 'Ananya Das',
    email: 'ananya.das@campus.edu',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    department: 'Bachelor of Design (B.Des)',
    year: '3rd Year (Semester 5)',
    status: 'stable',
    consent: {
      optedIn: true,
      shareIndicatorsWithCounselor: true,
      allowAggregatedAdminStats: true,
      consentDate: '2026-07-10',
    },
    checkIns: [
      {
        id: 'ck-401',
        studentId: 'stu-1405',
        date: '2026-08-01',
        weekNumber: 1,
        overallWellbeing: 5,
        academicStress: 2,
        sleepQuality: 4,
        energyLevel: 5,
        socialConnection: 5,
        concentration: 5,
        primaryTag: 'Routine',
      },
      {
        id: 'ck-402',
        studentId: 'stu-1405',
        date: '2026-08-08',
        weekNumber: 2,
        overallWellbeing: 4,
        academicStress: 2,
        sleepQuality: 4,
        energyLevel: 4,
        socialConnection: 5,
        concentration: 4,
        primaryTag: 'Routine',
      },
      {
        id: 'ck-403',
        studentId: 'stu-1405',
        date: '2026-08-15',
        weekNumber: 3,
        overallWellbeing: 5,
        academicStress: 2,
        sleepQuality: 5,
        energyLevel: 4,
        socialConnection: 4,
        concentration: 5,
        primaryTag: 'Projects',
      },
      {
        id: 'ck-404',
        studentId: 'stu-1405',
        date: '2026-08-21',
        weekNumber: 4,
        overallWellbeing: 5,
        academicStress: 2,
        sleepQuality: 4,
        energyLevel: 5,
        socialConnection: 5,
        concentration: 5,
        primaryTag: 'Routine',
        personalReflection: 'Studio work is going great. Good studio group vibe.',
      },
    ],
  },
  {
    id: 'stu-1512',
    anonymousCode: 'STU-1512',
    name: 'Kavya Nair',
    email: 'kavya.nair@campus.edu',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    department: 'Artificial Intelligence & Data Science',
    year: '2nd Year (Semester 4)',
    status: 'monitor',
    consent: {
      optedIn: true,
      shareIndicatorsWithCounselor: true,
      allowAggregatedAdminStats: true,
      consentDate: '2026-07-18',
    },
    checkIns: [
      {
        id: 'ck-501',
        studentId: 'stu-1512',
        date: '2026-08-01',
        weekNumber: 1,
        overallWellbeing: 4,
        academicStress: 2,
        sleepQuality: 4,
        energyLevel: 4,
        socialConnection: 4,
        concentration: 4,
      },
      {
        id: 'ck-502',
        studentId: 'stu-1512',
        date: '2026-08-08',
        weekNumber: 2,
        overallWellbeing: 4,
        academicStress: 3,
        sleepQuality: 3,
        energyLevel: 4,
        socialConnection: 4,
        concentration: 3,
      },
      {
        id: 'ck-503',
        studentId: 'stu-1512',
        date: '2026-08-15',
        weekNumber: 3,
        overallWellbeing: 3,
        academicStress: 4,
        sleepQuality: 3,
        energyLevel: 3,
        socialConnection: 3,
        concentration: 3,
      },
      {
        id: 'ck-504',
        studentId: 'stu-1512',
        date: '2026-08-21',
        weekNumber: 4,
        overallWellbeing: 3,
        academicStress: 4,
        sleepQuality: 3,
        energyLevel: 3,
        socialConnection: 4,
        concentration: 3,
        primaryTag: 'Exams',
        personalReflection: 'Midterms week approaching. Managing with study buddies.',
      },
    ],
  },
  {
    id: 'stu-1689',
    anonymousCode: 'STU-1689',
    name: 'Vikram Singh',
    email: 'vikram.singh@campus.edu',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    department: 'Bachelor of Commerce (B.Com)',
    year: '1st Year (Semester 1)',
    status: 'monitor',
    consent: {
      optedIn: true,
      shareIndicatorsWithCounselor: true,
      allowAggregatedAdminStats: true,
      consentDate: '2026-07-28',
    },
    checkIns: [
      {
        id: 'ck-601',
        studentId: 'stu-1689',
        date: '2026-08-08',
        weekNumber: 2,
        overallWellbeing: 4,
        academicStress: 2,
        sleepQuality: 4,
        energyLevel: 4,
        socialConnection: 4,
        concentration: 4,
      },
      {
        id: 'ck-602',
        studentId: 'stu-1689',
        date: '2026-08-15',
        weekNumber: 3,
        overallWellbeing: 4,
        academicStress: 3,
        sleepQuality: 3,
        energyLevel: 3,
        socialConnection: 3,
        concentration: 4,
      },
      {
        id: 'ck-603',
        studentId: 'stu-1689',
        date: '2026-08-21',
        weekNumber: 4,
        overallWellbeing: 3,
        academicStress: 3,
        sleepQuality: 2,
        energyLevel: 2,
        socialConnection: 3,
        concentration: 3,
        primaryTag: 'Health',
        personalReflection: 'Recovering from viral fever, felt fatigued during classes.',
      },
    ],
  },
  {
    id: 'stu-1724',
    anonymousCode: 'STU-1724',
    name: 'Siddharth Roy',
    email: 'siddharth.roy@campus.edu',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    department: 'Electronics & Communication',
    year: '4th Year (Semester 7)',
    status: 'stable',
    consent: {
      optedIn: true,
      shareIndicatorsWithCounselor: true,
      allowAggregatedAdminStats: true,
      consentDate: '2026-07-12',
    },
    checkIns: [
      {
        id: 'ck-701',
        studentId: 'stu-1724',
        date: '2026-08-01',
        weekNumber: 1,
        overallWellbeing: 4,
        academicStress: 3,
        sleepQuality: 3,
        energyLevel: 4,
        socialConnection: 4,
        concentration: 4,
      },
      {
        id: 'ck-702',
        studentId: 'stu-1724',
        date: '2026-08-08',
        weekNumber: 2,
        overallWellbeing: 4,
        academicStress: 3,
        sleepQuality: 4,
        energyLevel: 4,
        socialConnection: 4,
        concentration: 4,
      },
      {
        id: 'ck-703',
        studentId: 'stu-1724',
        date: '2026-08-15',
        weekNumber: 3,
        overallWellbeing: 4,
        academicStress: 3,
        sleepQuality: 3,
        energyLevel: 3,
        socialConnection: 4,
        concentration: 4,
      },
      {
        id: 'ck-704',
        studentId: 'stu-1724',
        date: '2026-08-21',
        weekNumber: 4,
        overallWellbeing: 4,
        academicStress: 3,
        sleepQuality: 4,
        energyLevel: 4,
        socialConnection: 4,
        concentration: 4,
        primaryTag: 'Projects',
      },
    ],
  },
];

export const CAMPUS_COHORT_STATS = {
  totalEnrolled: 248,
  totalOptedIn: 241, // 97.2% consent rate
  activeCheckInsThisWeek: 228,
  statusBreakdown: {
    stable: 183,
    monitor: 49,
    checkInRecommended: 16,
  },
  topElevatedFactors: [
    { factor: 'Academic & Project Deadlines', percentage: 42 },
    { factor: 'Sleep Disruption / Irregular Hours', percentage: 31 },
    { factor: 'First-Year Social Transition', percentage: 17 },
    { factor: 'Exam Anxiety', percentage: 10 },
  ],
  departmentBreakdown: [
    { name: 'Computer Science (CSE & BCA)', count: 96, flagRate: '9.3%', avgWellbeing: 3.4 },
    { name: 'Management & Commerce', count: 68, flagRate: '5.8%', avgWellbeing: 3.7 },
    { name: 'Design & Architecture', count: 44, flagRate: '4.5%', avgWellbeing: 4.1 },
    { name: 'Electronics & Mech Eng', count: 40, flagRate: '7.5%', avgWellbeing: 3.6 },
  ],
};
